//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class resturant_info
    {
        public int rest_ID { get; set; }
        public string rest_name { get; set; }
        public string rest_address { get; set; }
        public int rest_zipcode { get; set; }
        public string rest_phoneNumber { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public double rest_rating { get; set; }
    }
}
